/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import javax.swing.*;
/**
 *
 * @author OBAM EKONO KEVIN
 */
public class Coseillers extends javax.swing.JFrame {

    /**
     * Creates new form Coseillers
     */
    public Coseillers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab_mes_clients = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_client = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_actualiser = new javax.swing.JButton();
        btn_simulation = new javax.swing.JButton();
        btn_consulter_client = new javax.swing.JButton();
        btn_modifier_client = new javax.swing.JButton();
        btn_creer_client = new javax.swing.JButton();
        btn_gestion_patrimoine = new javax.swing.JButton();
        btn_virement = new javax.swing.JButton();
        btn_supprimer_client = new javax.swing.JButton();
        label_client_message = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_deconnexion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        footer_conseiller = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TABLEAU DE BORD POUR CONSEILLERS");
        setMaximumSize(new java.awt.Dimension(1138, 725));
        setMinimumSize(new java.awt.Dimension(1138, 725));
        setPreferredSize(new java.awt.Dimension(1138, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        tab_mes_clients.setLayout(null);

        table_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "null", "null", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_client);

        tab_mes_clients.add(jScrollPane1);
        jScrollPane1.setBounds(10, 111, 989, 380);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TABLEAU DES CLIENTS");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tab_mes_clients.add(jLabel2);
        jLabel2.setBounds(210, 60, 478, 28);
        jLabel2.getAccessibleContext().setAccessibleName("label_liste_client");

        btn_actualiser.setBackground(new java.awt.Color(204, 204, 0));
        btn_actualiser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_actualiser.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualiser.setText("ACTUALISER");
        btn_actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualiserActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_actualiser);
        btn_actualiser.setBounds(1000, 110, 120, 35);

        btn_simulation.setBackground(new java.awt.Color(102, 0, 102));
        btn_simulation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_simulation.setText("SIMULATIONS");
        btn_simulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simulationActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_simulation);
        btn_simulation.setBounds(1000, 360, 120, 34);

        btn_consulter_client.setBackground(new java.awt.Color(51, 255, 255));
        btn_consulter_client.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_consulter_client.setText("CONSULTER");
        btn_consulter_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consulter_clientActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_consulter_client);
        btn_consulter_client.setBounds(1000, 260, 120, 34);

        btn_modifier_client.setBackground(new java.awt.Color(255, 102, 0));
        btn_modifier_client.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_modifier_client.setText("MODIFIER");
        btn_modifier_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_clientActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_modifier_client);
        btn_modifier_client.setBounds(1000, 210, 120, 34);

        btn_creer_client.setBackground(new java.awt.Color(51, 255, 51));
        btn_creer_client.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_creer_client.setText("NOUVEAU");
        btn_creer_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_creer_clientActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_creer_client);
        btn_creer_client.setBounds(1000, 160, 120, 34);

        btn_gestion_patrimoine.setBackground(new java.awt.Color(255, 255, 0));
        btn_gestion_patrimoine.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_gestion_patrimoine.setText("G.PATRIMOINE");
        btn_gestion_patrimoine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestion_patrimoineActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_gestion_patrimoine);
        btn_gestion_patrimoine.setBounds(1000, 310, 120, 34);

        btn_virement.setBackground(new java.awt.Color(204, 204, 204));
        btn_virement.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_virement.setText("VIREMENT");
        btn_virement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_virementActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_virement);
        btn_virement.setBounds(1000, 410, 120, 34);

        btn_supprimer_client.setBackground(new java.awt.Color(190, 3, 3));
        btn_supprimer_client.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_supprimer_client.setText("SUPPRIMER");
        btn_supprimer_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer_clientActionPerformed(evt);
            }
        });
        tab_mes_clients.add(btn_supprimer_client);
        btn_supprimer_client.setBounds(1000, 460, 120, 34);

        label_client_message.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        label_client_message.setForeground(new java.awt.Color(255, 255, 255));
        label_client_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab_mes_clients.add(label_client_message);
        label_client_message.setBounds(10, 10, 1040, 40);

        jTabbedPane1.addTab("MES CLIENTS", tab_mes_clients);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("FORMULAIRE CLIENT", jPanel2);

        jPanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modification /Consultation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 204))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 11, 1110, 250);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTabbedPane2.addTab("tab1", jScrollPane2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTabbedPane2.addTab("tab2", jScrollPane3);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTabbedPane2.addTab("tab3", jScrollPane4);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(20, 270, 560, 230);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Creation Compte", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1);
        jTextField1.setBounds(160, 60, 128, 30);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(10, 60, 128, 30);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(320, 60, 128, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compte Epargne", "Compte Courant", " " }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(110, 100, 220, 20);

        jLabel3.setText("Solde");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(330, 40, 90, 20);

        jLabel4.setText("Date de Creation");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 34, 90, 20);

        jLabel5.setText("Numero Compte");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(180, 40, 90, 20);

        jTabbedPane3.addTab("tab4", jPanel4);

        jPanel1.add(jTabbedPane3);
        jTabbedPane3.setBounds(650, 280, 470, 220);

        jTabbedPane1.addTab("TRANSACTIONS", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 107, 1130, 530);

        btn_deconnexion.setBackground(new java.awt.Color(0, 0, 255));
        btn_deconnexion.setForeground(new java.awt.Color(255, 0, 51));
        btn_deconnexion.setText("Deconnexion");
        btn_deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deconnexionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deconnexion);
        btn_deconnexion.setBounds(970, 70, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/bannervrai copie.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1130, 110);

        footer_conseiller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/footer copie.png"))); // NOI18N
        getContentPane().add(footer_conseiller);
        footer_conseiller.setBounds(0, 650, 1130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualiserActionPerformed
        // mettre code pour actualiser le tableau des clients d'un conseiller
        
        label_client_message.setText("Actualisation du tableau effectué");
        
    }//GEN-LAST:event_btn_actualiserActionPerformed

    private void btn_creer_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_creer_clientActionPerformed
        // mettre code de lancement du formulaire de creation d'un client
        InscriptionClient n = new InscriptionClient();
        n.setTextin_adresse("bonjour");
n.setTextin_nom("Obam Ekono");
         n.setVisible(true);
      
        
        
       
         label_client_message.setText("Creation d'un nouveau client effectué");
    }//GEN-LAST:event_btn_creer_clientActionPerformed

    private void btn_modifier_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_clientActionPerformed
        // mettre code qui lance le formulaire de modification d'un client
        
         label_client_message.setText("Modification d'un client effectué");
         
         
        
    }//GEN-LAST:event_btn_modifier_clientActionPerformed

    private void btn_consulter_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consulter_clientActionPerformed
        // mettre ici code lancement d'un fenetre de consultation des information d'un client
        
        label_client_message.setText("Consultation d'un client effectué");
    }//GEN-LAST:event_btn_consulter_clientActionPerformed

    private void btn_gestion_patrimoineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestion_patrimoineActionPerformed
        // mettre le module de gestion de patrimoine en verifiant si le client repond aux criteres sinon afficher message sur label_client_message
        label_client_message.setText("Gestion du patrimoine d'un client effectué");
        
    }//GEN-LAST:event_btn_gestion_patrimoineActionPerformed

    private void btn_simulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simulationActionPerformed
        // lancement de la fenetre de simulation des credits
        
        label_client_message.setText("Simulation effectué");
    }//GEN-LAST:event_btn_simulationActionPerformed

    private void btn_virementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_virementActionPerformed
        // mettre le lancement du module de virement compte a compte
        label_client_message.setText("Virement effectué");
    }//GEN-LAST:event_btn_virementActionPerformed

    private void btn_supprimer_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer_clientActionPerformed
        // mettre le module de suppression d'un client avec suppression des comptes et desactivation des cartes de credit
        
        label_client_message.setText("Suppression avec desactivation des compte et cartes d'un client effectué");
    }//GEN-LAST:event_btn_supprimer_clientActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deconnexionActionPerformed
        // ce code gere la deconnexion d'un utilisateur:
        
        Login n = new Login();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_deconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coseillers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coseillers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coseillers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coseillers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coseillers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualiser;
    private javax.swing.JButton btn_consulter_client;
    private javax.swing.JButton btn_creer_client;
    private javax.swing.JButton btn_deconnexion;
    private javax.swing.JButton btn_gestion_patrimoine;
    private javax.swing.JButton btn_modifier_client;
    private javax.swing.JButton btn_simulation;
    private javax.swing.JButton btn_supprimer_client;
    private javax.swing.JButton btn_virement;
    private javax.swing.JLabel footer_conseiller;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel label_client_message;
    private javax.swing.JPanel tab_mes_clients;
    private javax.swing.JTable table_client;
    // End of variables declaration//GEN-END:variables
}
