/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author OBAM EKONO KEVIN
 */
public class InscriptionClient extends javax.swing.JFrame {

    /**
     * Creates new form InscriptionClient
     */
    public InscriptionClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        in_tel = new javax.swing.JTextField();
        in_nom = new javax.swing.JTextField();
        label_code_postal = new javax.swing.JLabel();
        in_email = new javax.swing.JTextField();
        in_profession = new javax.swing.JTextField();
        in_ville = new javax.swing.JTextField();
        in_adresse = new javax.swing.JTextField();
        in_code_postal = new javax.swing.JTextField();
        in_prenom = new javax.swing.JTextField();
        btn_nouveau = new javax.swing.JButton();
        btn_effacer = new javax.swing.JButton();
        btn_enregistrer = new javax.swing.JButton();
        label_g_nom = new javax.swing.JLabel();
        label_g_prenom = new javax.swing.JLabel();
        label_g_tel = new javax.swing.JLabel();
        label_g_email = new javax.swing.JLabel();
        label_g_profession = new javax.swing.JLabel();
        label_g_ville = new javax.swing.JLabel();
        label_g_adresse = new javax.swing.JLabel();
        label_bad_nom = new javax.swing.JLabel();
        label_bad_prenom = new javax.swing.JLabel();
        label_bad_tel = new javax.swing.JLabel();
        label_bad_email = new javax.swing.JLabel();
        label_bad_profession = new javax.swing.JLabel();
        label_bad_ville = new javax.swing.JLabel();
        label_message = new javax.swing.JLabel();
        label_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULAIRE D'INSCRIPTION D'UN CLIENT");
        setMaximumSize(new java.awt.Dimension(640, 650));
        setMinimumSize(new java.awt.Dimension(640, 650));
        setPreferredSize(new java.awt.Dimension(640, 650));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(in_tel);
        in_tel.setBounds(190, 260, 400, 30);
        getContentPane().add(in_nom);
        in_nom.setBounds(190, 180, 400, 30);
        getContentPane().add(label_code_postal);
        label_code_postal.setBounds(590, 460, 30, 30);
        getContentPane().add(in_email);
        in_email.setBounds(190, 300, 400, 30);
        getContentPane().add(in_profession);
        in_profession.setBounds(190, 340, 400, 30);
        getContentPane().add(in_ville);
        in_ville.setBounds(190, 380, 400, 30);
        getContentPane().add(in_adresse);
        in_adresse.setBounds(190, 420, 400, 30);
        getContentPane().add(in_code_postal);
        in_code_postal.setBounds(190, 460, 400, 30);
        getContentPane().add(in_prenom);
        in_prenom.setBounds(190, 220, 400, 30);

        btn_nouveau.setBackground(new java.awt.Color(0, 51, 255));
        btn_nouveau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_nouveau.setText("NOUVEAU");
        btn_nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nouveauActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nouveau);
        btn_nouveau.setBounds(490, 520, 110, 40);

        btn_effacer.setBackground(new java.awt.Color(255, 0, 0));
        btn_effacer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_effacer.setText("EFFACER");
        btn_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_effacerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_effacer);
        btn_effacer.setBounds(30, 520, 110, 40);

        btn_enregistrer.setBackground(new java.awt.Color(51, 255, 0));
        btn_enregistrer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_enregistrer.setText("ENREGISTRER");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enregistrer);
        btn_enregistrer.setBounds(250, 520, 110, 40);
        getContentPane().add(label_g_nom);
        label_g_nom.setBounds(590, 180, 30, 30);
        getContentPane().add(label_g_prenom);
        label_g_prenom.setBounds(590, 220, 30, 30);
        getContentPane().add(label_g_tel);
        label_g_tel.setBounds(590, 260, 30, 30);
        getContentPane().add(label_g_email);
        label_g_email.setBounds(590, 300, 30, 30);
        getContentPane().add(label_g_profession);
        label_g_profession.setBounds(590, 340, 30, 30);
        getContentPane().add(label_g_ville);
        label_g_ville.setBounds(590, 380, 30, 30);
        getContentPane().add(label_g_adresse);
        label_g_adresse.setBounds(590, 420, 30, 30);
        getContentPane().add(label_bad_nom);
        label_bad_nom.setBounds(160, 180, 30, 30);
        getContentPane().add(label_bad_prenom);
        label_bad_prenom.setBounds(160, 220, 30, 30);
        getContentPane().add(label_bad_tel);
        label_bad_tel.setBounds(160, 260, 30, 30);
        getContentPane().add(label_bad_email);
        label_bad_email.setBounds(160, 300, 30, 30);
        getContentPane().add(label_bad_profession);
        label_bad_profession.setBounds(160, 340, 30, 30);
        getContentPane().add(label_bad_ville);
        label_bad_ville.setBounds(160, 380, 30, 30);

        label_message.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_message.setForeground(new java.awt.Color(255, 102, 0));
        label_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(label_message);
        label_message.setBounds(200, 144, 390, 30);

        label_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/inscription client copie.png"))); // NOI18N
        getContentPane().add(label_bg);
        label_bg.setBounds(0, 0, 640, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_effacerActionPerformed
        // mettre ici le code qui permet de vider tout les champs du formulaire
        
        
    }//GEN-LAST:event_btn_effacerActionPerformed

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        // mettre ici le code qui permet de verifier le formulaire et enregistrer si c'est bon afficher les erreurs sinon et bloquer le bouton apres une seule action:
        
        
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_nouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nouveauActionPerformed
        // permet de debloquer le bouton d'enregistrement pour un autre enregistrement
        
        
    }//GEN-LAST:event_btn_nouveauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscriptionClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriptionClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_effacer;
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_nouveau;
    private javax.swing.JTextField in_adresse;
    private javax.swing.JTextField in_code_postal;
    private javax.swing.JTextField in_email;
    private javax.swing.JTextField in_nom;
    private javax.swing.JTextField in_prenom;
    private javax.swing.JTextField in_profession;
    private javax.swing.JTextField in_tel;
    private javax.swing.JTextField in_ville;
    private javax.swing.JLabel label_bad_email;
    private javax.swing.JLabel label_bad_nom;
    private javax.swing.JLabel label_bad_prenom;
    private javax.swing.JLabel label_bad_profession;
    private javax.swing.JLabel label_bad_tel;
    private javax.swing.JLabel label_bad_ville;
    private javax.swing.JLabel label_bg;
    private javax.swing.JLabel label_code_postal;
    private javax.swing.JLabel label_g_adresse;
    private javax.swing.JLabel label_g_email;
    private javax.swing.JLabel label_g_nom;
    private javax.swing.JLabel label_g_prenom;
    private javax.swing.JLabel label_g_profession;
    private javax.swing.JLabel label_g_tel;
    private javax.swing.JLabel label_g_ville;
    private javax.swing.JLabel label_message;
    // End of variables declaration//GEN-END:variables

    String getTextin_adresse() {
     return in_adresse.getText()  ; //To change body of generated methods, choose Tools | Templates.
    }

    void setTextin_adresse(String n) {
        this.in_adresse.setText(n); //To change body of generated methods, choose Tools | Templates.
    }
    String getTextin_nom() {
     return in_nom.getText()  ; //To change body of generated methods, choose Tools | Templates.
    }

    void setTextin_nom(String n) {
        this.in_nom.setText(n); //To change body of generated methods, choose Tools | Templates.
    }
}
