/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import java.awt.EventQueue;

import javax.swing.JOptionPane;

import cm.objis.promo3.proxybank.service.IParametrageService;
import cm.objis.promo3.proxybank.service.ParametrageServiceImpl;

import java.awt.Color;

/**
 *
 * @author OBAM EKONO KEVIN
 */
public class Login extends javax.swing.JFrame {

    /**
	 * 
	 */
	private IParametrageService service;
	private static final long serialVersionUID = -6766367744927448596L;
	/**
     * Creates new form Login
     */
    public Login() {
    	service = new ParametrageServiceImpl();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        in_username = new javax.swing.JTextField();
        in_password = new javax.swing.JPasswordField();
        in_fonction = new javax.swing.JComboBox<>();
        btn_effacer = new javax.swing.JButton();
        btn_connecter1 = new javax.swing.JButton();
        label_message = new javax.swing.JLabel();
        label_message1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(655, 525, 525, 525));
        setMaximumSize(new java.awt.Dimension(655, 525));
        setMinimumSize(new java.awt.Dimension(655, 525));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(in_username);
        in_username.setBounds(290, 220, 280, 30);

        in_password.setToolTipText("");
        getContentPane().add(in_password);
        in_password.setBounds(290, 260, 280, 30);

        in_fonction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrateur", "Conseillr", "Gerant" }));
        getContentPane().add(in_fonction);
        in_fonction.setBounds(290, 300, 150, 30);

        btn_effacer.setBackground(new java.awt.Color(255, 0, 0));
        btn_effacer.setText("EFFACER");
        btn_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_effacerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_effacer);
        btn_effacer.setBounds(20, 410, 170, 40);

        btn_connecter1.setBackground(new java.awt.Color(0, 255, 51));
        btn_connecter1.setText("VALIDER");
        btn_connecter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connecter1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connecter1);
        btn_connecter1.setBounds(450, 410, 170, 40);

        label_message.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_message.setForeground(new java.awt.Color(255, 0, 51));
        label_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(label_message);
        label_message.setBounds(60, 370, 530, 30);

        label_message1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_message1.setForeground(new java.awt.Color(102, 255, 51));
        label_message1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(label_message1);
        label_message1.setBounds(60, 370, 530, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/login copiev2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_effacerActionPerformed
        // mettre code qui permet d effacer les champs
        in_username.setText("");
        in_password.setText("");
        label_message.setText("");
    }//GEN-LAST:event_btn_effacerActionPerformed

    private void btn_connecter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connecter1ActionPerformed
        // module de connexion apres verification et redirection en fonction des users
         
    	String login = "";
		String password = "";
		
		/******    VERIFICATION DE N'AVOIR PAS DE CHAMPS VIDES    *****/
		if(in_username.getText().trim().equals("")){
			JOptionPane.showMessageDialog(null, "Ce champ ne doit pas etre vide", "ALERTE", 1);
			in_username.requestFocus();
			return;
		}else {
			login = in_username.getText();
		}
    	
    	String username ="Jamal" ;
  String Password ="informatiques";
   String fonction ="Conseillr" ;
        if(username.equals(in_username.getText()) && Password.equals(in_password.getText())){
        
        Coseillers n = new Coseillers();
        n.setVisible(true);
        this.dispose();
        
        }else{
        
        label_message.setText("Votre Nom d' Utilisateur ou mot de passe n'est pas bon");
        
        }
        
        
        
    }//GEN-LAST:event_btn_connecter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_connecter1;
    private javax.swing.JButton btn_effacer;
    private javax.swing.JComboBox<String> in_fonction;
    private javax.swing.JPasswordField in_password;
    private javax.swing.JTextField in_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_message;
    private javax.swing.JLabel label_message1;
    // End of variables declaration//GEN-END:variables
}
